#! /bin/sh

# Load sxhkd
pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Code desktop='^3' state=tiled follow=on
bspc rule -a firefox desktop='^6' state=tiled follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off


# Border values
bspc config active_border_color "#0d93df"
bspc config normal_border_color "#09529c"
bspc config focused_border_color '#0d93df'
bspc config border_width 3


# Autostart applications
picom --config $HOME/.config/picom/picom.conf &
dunst &
polybar &
feh --bg-scale $HOME/.config/background.png &
xsetroot -cursor_name left_ptr &
